export enum Permission {
    MANAGE_COMPANY = 'MANAGE_COMPANY',
    MANAGE_USERS = 'MANAGE_USERS',
    CREATE_TEMPLATE = 'CREATE_TEMPLATE',
    SEND_DOCUMENT = 'SEND_DOCUMENT',
    VIEW_AUDIT = 'VIEW_AUDIT'
}
